server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: ad-service
          uri: http://localhost:8083
          predicates:
            - Path=/ads/**
        - id: admin-service
          uri: http://localhost:8084
          predicates:
            - Path=/admin/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservice-platform

keycloak:
  auth-server-url: http://localhost:8080
  realm: microservice-platform
  resource: api-gateway-client
  public-client: false
  credentials:
    secret: gateway-secret-key-here

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/auth/**
        - id: ad-service
          uri: http://ad-service:8083
          predicates:
            - Path=/ads/**
        - id: admin-service
          uri: http://admin-service:8084
          predicates:
            - Path=/admin/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_URL}
  resource: ${KEYCLOAK_CLIENT_ID}
  public-client: false
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}